### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by Xaviju** [Frontaneria/frontaneria.github.io#1]
Cerremos el tema del logo. Este podría ser el proceso:

1. Cada una de las personas que ha creado un logo y desea ponerlo como propuesta de logo oficial de Frontaneros puede subir su logo en esta issue. 
2. Cada persona puede votar los logos como le de la gana porque nadie lo va a contar pero lo ideal sería votar no más de 2. Para votar utiliza un símbolo 👍 a falta de Paulos Coelhos.
3. Una vez terminadas las votaciones (¿la semana que viene?) decidimos cual es el ganador y este se sube en SVG.
4. Sobre el ganador podemos proponer ligeras variaciones que ejecuta el diseñador del logo en función de su criterio libre y básicamente si le mola.
5. Ponemos el logo final everywhere y nos quitamos esta movida de encima.

**Comment by Angelmmiguel** [comment]
![Logo](https://cloud.githubusercontent.com/assets/4056725/23354776/fd7560d8-fcd2-11e6-9a79-aea1d56dd00e.png)

## Versión oscura
![Oscuro](https://cloud.githubusercontent.com/assets/4056725/23354777/fd758fb8-fcd2-11e6-9670-66202dbfa805.png)

**Comment by robergd** [comment]
## Tonos pastel
![frontaneros 2](https://cloud.githubusercontent.com/assets/579726/23354975/d412a8ee-fcd3-11e6-91b1-e89db2a0446a.png)

**Comment by javierlopezdeancos** [comment]
<img width="240" alt="captura de pantalla 2017-02-27 a las 11 44 32" src="https://cloud.githubusercontent.com/assets/1202463/23358452/4442979c-fce2-11e6-99fb-350442382e14.png"><img width="300" alt="captura de pantalla 2017-02-27 a las 11 44 32" src="https://cloud.githubusercontent.com/assets/1202463/23371277/dea7a5fe-fd17-11e6-8a8d-d8e4ec1a5b48.png">

**Comment by elenatorro** [comment]
Preview con sombra y girado:
![frontaneros_1](https://cloud.githubusercontent.com/assets/3824953/23362993/a5eb6f58-fcf8-11e6-96ba-6c62bc24781c.png)

Otras variaciones de colores:
![frontaneros_logos](https://cloud.githubusercontent.com/assets/3824953/23363020/cee7b9c0-fcf8-11e6-9aee-d57bf3da16c5.png)

**Comment by Xaviju** [comment]
Ya tenemos ganadora, es @elenatorro !!
Siguiendo con lo acordado:
@elenatorro -> Una vez terminadas las votaciones (¿la semana que viene?) decidimos cual es el ganador y este se sube en SVG.
Resto -> Sobre el ganador podemos proponer ligeras variaciones que ejecuta el diseñador del logo en función de su criterio libre y básicamente si le mola.

**Comment by Xaviju** [comment]
A mí me gustaría verlo en modo icono [16x16] o [32x32] sobre diferentes fondos y cual sería su uso correcto.
También me gustaría saber qué color deberíamos usar por defecto.
Me parece demasiado detallado, ¿podríamos simplificarlo un poco?

My two cents @elenatorro

**Comment by danicatalan** [comment]
Felicidades @elenatorro, para mi, la opción mas original y representativa! ;)

**Comment by danicatalan** [comment]
A mi me gustaría ver como se comporta en tamaños pequeños, creo que con eso nos daremos cuenta que hace falta quitar detalles y el outline.

**Comment by danicatalan** [comment]
Sobre el color, mi favorito es el amarillo.

**Comment by elenatorro** [comment]
¡Genial! Esta tarde subiré sugerencias. Os paso también los SVG actuales por si alguien quiere juguetear y hacer alguna modificación.

**Comment by javierlopezdeancos** [comment]
gracias @elenatorro

**Comment by Angelmmiguel** [comment]
La verdad que si, es el logo más representativo :D. A mi también me gusta el color amarillo.

**Comment by IgnaciodeNuevo** [comment]
Pensando en el futuro y aunque mi favorito es el amarillo, si se hacen pegatinas por ejemplo o cualquier otra cosa impresa sea digital o en una imprenta offset el amarillo es el que más problemas da.

**Comment by elenatorro** [comment]
![frontaneros_logo_amarillo_rosa_circulo_16](https://cloud.githubusercontent.com/assets/3824953/23679712/132b3f58-0389-11e7-8b0f-c3e6b81b5ce3.png)
![frontaneros_logo_gris_rosa_circulo_16](https://cloud.githubusercontent.com/assets/3824953/23679767/37268ffc-0389-11e7-993e-b248fc566cc4.png)
![frontaneros_logo_amarillo_turquesa_circulo_16](https://cloud.githubusercontent.com/assets/3824953/23679716/165f60fa-0389-11e7-88df-6018bb0b1043.png)
![frontaneros_logo_gris_azul_circulo_16](https://cloud.githubusercontent.com/assets/3824953/23679754/31c0280c-0389-11e7-8a1f-a405c780b348.png)
![frontaneros_logo_amarillo_azul_oscuro_circulo_16](https://cloud.githubusercontent.com/assets/3824953/23680009/f91d861a-0389-11e7-9f67-1f405a1dfcc5.png)
![frontaneros_logo_gris_azuloscuro_circulo_16](https://cloud.githubusercontent.com/assets/3824953/23680002/f53f42fe-0389-11e7-9291-bb523cd031b5.png)
![frontaneros_logo_amarillo_violeta_circulo_16](https://cloud.githubusercontent.com/assets/3824953/23680065/37125ec8-038a-11e7-8168-02fc5e73496e.png)
![frontaneros_logo_gris_violeta_circulo_16](https://cloud.githubusercontent.com/assets/3824953/23680077/3ce1fd36-038a-11e7-839a-caac748622fe.png)

Logo en chiquitín:
![frontaneros_logo_amarillo_turquesa_circulo_sombra_32](https://cloud.githubusercontent.com/assets/3824953/23680747/a256382e-038c-11e7-9ffe-2c6919c6eb75.png)
![frontaneros_logo_amarillo_turquesa_circulo_sombra_16](https://cloud.githubusercontent.com/assets/3824953/23680787/ca17a94c-038c-11e7-9428-47ab98773e14.png)
![frontaneros_logo_gris_gris_circulo_32px](https://cloud.githubusercontent.com/assets/3824953/23680896/2c82c4fe-038d-11e7-990c-30099382aa68.png)
![frontaneros_logo_gris_gris_circulo_16px](https://cloud.githubusercontent.com/assets/3824953/23680916/36d5c01e-038d-11e7-9db0-5ac122681216.png)

**Comment by elenatorro** [comment]
Si queréis algún color en especial o queréis subir alguna sugerencia del logo, por mí perfect :)

**Comment by danicatalan** [comment]
@elenatorro por donde anda el svg?

**Comment by IgnaciodeNuevo** [comment]
Amarillo sobre fucsia o sobre azul (L)

**Comment by jaicab** [comment]
![image](https://cloud.githubusercontent.com/assets/1174434/24108732/c7d77dd6-0d8e-11e7-9f7a-6cd7ac8f44ec.png)
Le he dado un par de vueltas y a mi me gusta con esta posicion y un color asi crema de fondo. Sorry @elenatorro si me lo he cargado pero le he dado un par de toques a los bordes 😅

**Comment by javierlopezdeancos** [comment]
mola el proceso colaborativo

**Comment by IgnaciodeNuevo** [comment]
@jaicab Yo le quitaría detalle (circulitos pequeños). Cuando se reduce no se verán bien o en su defecto haría la versión para tamaños grandes y otra para tamaños pequeños.
