### ISSUE TITLE
Crear el boilerplate para la web

### ISSUE THREAD

**Issue by Angelmmiguel** [Frontaneria/frontaneria.github.io#2]
Finalmente, la web de Frontaneros se va a desarrollar con [Jekyll](https://jekyllrb.com/). 

Lo primero es crear el boilerplate de la aplicación sobre la que empezar a trabajar. Esto es, un proyecto base con todos los ficheros de plantillas y las instrucciones sobre como ejecutar el servidor y desarrollar nuevas funcionalidades.

**Comment by paulmelero** [comment]
Ya está creado. Lo cierro
