### ISSUE TITLE
Cambio de nombre de la web a Frontanería (frontaneria)

### ISSUE THREAD

**Issue by paulmelero** [Frontaneria/frontaneria.github.io#5]
Como se votó en su día
![image](https://user-images.githubusercontent.com/6775220/30503626-39343014-9a6b-11e7-923b-a42ee19676ed.png)

**Comment by IgnaciodeNuevo** [comment]
A ver si puede hacerlo @nucliweb cuando vuelva o @jaicab

**Comment by Angelmmiguel** [comment]
Habría que hacer el cambio antes de publicar nada, para no tener luego que cambiar la URL del site :)

**Comment by jaicab** [comment]
Hecho! 👍
